apiVersion: v1
kind: Service
metadata:
  name: nginx-interface-ens192-service
  annotations:
    kube-vip.io/serviceInterface: ens192
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP